### ISSUE TITLE
I am trying to make it work

### ISSUE THREAD

**Issue by kanglinyao** [ich777/docker-quake3#1]
What is the data directory for the container. I bind the /quake3 in the container to /opt/q3server on my server partition and copied baseq3 and missionpack to that folder, but the server is not working. 

Also I have a suggestion for this quake3 server container.
Could you use Spearmint quake3 to replace the original quake3?

**Comment by ich777** [comment]
Sorry haven't got time to add the discription but will do that in the next hour i think...
Here is a short description from unraid docker description:
PK3 Files: After the container started the first time you have to copy your pak*.pk3 files from your Quake III Arena directory into your server directory: .../.q3a/baseq3/ (i strongly recommend you to place all your pak*.pk3 files into it) after that simply restart the container and it would start the server.

Also can you please explain me what the differences are? I'm doing the containers just as hobby and on user requests...
Here the link to the forum thread:
https://forums.unraid.net/topic/79530-support-ich777-gameserver-dockers/

**Comment by ich777** [comment]
@kanglinyao 
Discription updated hope it works for you, please report back ;)

**Comment by kanglinyao** [comment]
> @kanglinyao
> Discription updated hope it works for you, please report back ;)

Thank you so much for the quick reply. I will give it a try.
